services:
  postgres:
    image: 'postgres:12'
    container_name: aeroadventures_db
    environment:
      - 'POSTGRES_DB=${MY_POSTGRES_DB}'
      - 'POSTGRES_PASSWORD=${MY_POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${MY_POSTGRES_USER}'
    volumes:
      - my_postgres_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
volumes:
  my_postgres_data: